Failure in python_err1.py:

  The CHECKERR on line 6 wants:
    BETA

  which failed to match line stderr:1:
    ALPHA

  Context:
    ALPHA <= does not match 'BETA'
    GAMMA1
    GAMMA2
    GAMMA3
    GAMMA4
    GAMMA5

  when running command:
    /usr/bin/python python_err1.py
